/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salon.indeks;

import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import salon.koneksi.koneksi;

/**
 *
 * @author Muhammad Husni Farid
 */
public class laporan extends javax.swing.JInternalFrame {

    /**
     * Creates new form laporan
     */
    public laporan() {
        initComponents();
        tlaporan();
    }
    
    
    private void tlaporan(){
       DefaultTableModel tlayanan1 = new DefaultTableModel();
            tlayanan1.addColumn("Kode Pesanan");
            tlayanan1.addColumn("Nama Layanan");
            tlayanan1.addColumn("Member");
            tlayanan1.addColumn("Harga");
            tlayanan1.addColumn("Tanggal Transaksi");

         
            try{
                Connection c = koneksi.getConnection();
                String sql="SELECT * FROM `tregist`";
                Statement s = c.createStatement();
                ResultSet rs = s.executeQuery(sql);
                while (rs.next())
                {
                tlayanan1.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
                });
                }
                tbllaporan.setModel(tlayanan1);
                } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Ada Kesalahan");
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbllaporan = new javax.swing.JTable();
        panelGlass1 = new usu.widget.glass.PanelGlass();
        cmbharian = new uz.ncipro.calendar.JDateTimePicker();
        tmbharian = new javax.swing.JButton();
        cmbminggu1 = new uz.ncipro.calendar.JDateTimePicker();
        cmbminggu2 = new uz.ncipro.calendar.JDateTimePicker();
        tmbminggu = new javax.swing.JButton();
        cmbbulan = new uz.ncipro.calendar.JDateTimePicker();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logo1 = new desain.logo();
        printharian = new javax.swing.JButton();

        setClosable(true);
        setTitle("LAPORAN TRANSAKSI");

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.setFocusCycleRoot(true);

        tbllaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(tbllaporan);

        cmbharian.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "  2016-06-20" }));
        cmbharian.setDisplayFormat("  yyyy-MM-dd");

        tmbharian.setText("Harian");
        tmbharian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmbharianActionPerformed(evt);
            }
        });

        cmbminggu1.setDisplayFormat("  yyyy-MM-ww");
        cmbminggu1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbminggu1PropertyChange(evt);
            }
        });

        cmbminggu2.setDisplayFormat("  yyyy-MM-dd");

        tmbminggu.setText("Mingguan");
        tmbminggu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmbmingguActionPerformed(evt);
            }
        });

        cmbbulan.setDisplayFormat("  yyyy-MM\n");

        jButton3.setText("Bulanan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("s/d");

        javax.swing.GroupLayout panelGlass1Layout = new javax.swing.GroupLayout(panelGlass1);
        panelGlass1.setLayout(panelGlass1Layout);
        panelGlass1Layout.setHorizontalGroup(
            panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass1Layout.createSequentialGroup()
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGlass1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(cmbminggu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cmbminggu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGlass1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(cmbharian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGlass1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(cmbbulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tmbminggu)
                    .addComponent(tmbharian, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        panelGlass1Layout.setVerticalGroup(
            panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmbharian, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(cmbharian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmbminggu, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(cmbminggu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbminggu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(cmbbulan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Laporan Transaksi");

        logo1.setFocusable(false);

        javax.swing.GroupLayout logo1Layout = new javax.swing.GroupLayout(logo1);
        logo1.setLayout(logo1Layout);
        logo1Layout.setHorizontalGroup(
            logo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        logo1Layout.setVerticalGroup(
            logo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
        );

        printharian.setText("Print");
        printharian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printharianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 283, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187)
                        .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelGlass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(printharian)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(21, Short.MAX_VALUE)
                        .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175)
                        .addComponent(printharian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelGlass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tmbharianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbharianActionPerformed
        // TODO add your handling code here:
            DefaultTableModel tlayanan1 = new DefaultTableModel();
            tlayanan1.addColumn("Kode Pesanan");
            tlayanan1.addColumn("Nama Layanan");
            tlayanan1.addColumn("Member");
            tlayanan1.addColumn("Harga");
            tlayanan1.addColumn("Tanggal Transaksi");          

            try{
                Connection c = koneksi.getConnection();
                String sql="SELECT * FROM `tregist` WHERE tgl='"+cmbharian.getSelectedItem()+"'";
                Statement s = c.createStatement();
                ResultSet rs = s.executeQuery(sql);
                while (rs.next())
                {
                tlayanan1.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),                
                });
                }
                tbllaporan.setModel(tlayanan1);
                } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Ada Kesalahan");
                }
    }//GEN-LAST:event_tmbharianActionPerformed

    private void cmbminggu1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbminggu1PropertyChange
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cmbminggu1PropertyChange

    private void tmbmingguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbmingguActionPerformed
        // TODO add your handling code here:
           DefaultTableModel tlayanan1 = new DefaultTableModel();
            tlayanan1.addColumn("Kode Pesanan");
            tlayanan1.addColumn("Nama Layanan");
            tlayanan1.addColumn("Member");
            tlayanan1.addColumn("Harga");
            tlayanan1.addColumn("Tanggal Transaksi");           

            try{
                Connection c = koneksi.getConnection();
                String sql="SELECT * FROM `tregist` where (tgl between '"+cmbminggu1.getSelectedItem()+"' and '"+cmbminggu2.getSelectedItem()+"')";
                Statement s = c.createStatement();
                ResultSet rs = s.executeQuery(sql);
                while (rs.next())
                {
                tlayanan1.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),                
                });
                }
                tbllaporan.setModel(tlayanan1);
                } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Ada Kesalahan");
                }                                       
    }//GEN-LAST:event_tmbmingguActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel tlayanan1 = new DefaultTableModel();
            tlayanan1.addColumn("Kode Transaksi");
            tlayanan1.addColumn("Nama Layanan");
            tlayanan1.addColumn("Kode Member");
            tlayanan1.addColumn("Harga");
            tlayanan1.addColumn("Tanggal Transaksi");           

            try{
                Connection c = koneksi.getConnection();
                cmbbulan.setDisplayFormat("MM");
                String sql="SELECT * FROM `tregist` where DATE_FORMAT(tgl,'%m')='"+cmbbulan.getSelectedItem()+"'";
                Statement s = c.createStatement();
                ResultSet rs = s.executeQuery(sql);
                while (rs.next())
                {
                tlayanan1.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),                
                });
                }
                tbllaporan.setModel(tlayanan1);
                cmbbulan.setDisplayFormat("yyyy-MM");
                } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Ada Kesalahan");
                }  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void printharianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printharianActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null,"Ada Kesalahan");
    }//GEN-LAST:event_printharianActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private uz.ncipro.calendar.JDateTimePicker cmbbulan;
    private uz.ncipro.calendar.JDateTimePicker cmbharian;
    private uz.ncipro.calendar.JDateTimePicker cmbminggu1;
    private uz.ncipro.calendar.JDateTimePicker cmbminggu2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private desain.logo logo1;
    private usu.widget.glass.PanelGlass panelGlass1;
    private javax.swing.JButton printharian;
    private javax.swing.JTable tbllaporan;
    private javax.swing.JButton tmbharian;
    private javax.swing.JButton tmbminggu;
    // End of variables declaration//GEN-END:variables
}
