/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salon.indeks;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import salon.koneksi.koneksi;

/**
 *
 * @author Muhammad Husni Farid
 */
public final class member extends javax.swing.JInternalFrame {

    /**
     * Creates new form member
     */
    public member() {
        initComponents();
        tabmember();
        AutoNomor();
    }

    
    
    private void tabmember(){
       DefaultTableModel tlayanan1 = new DefaultTableModel();
            tlayanan1.addColumn("Kode Member");
            tlayanan1.addColumn("Nama");
            tlayanan1.addColumn("Jenis Kelamin");
            tlayanan1.addColumn("tanggal Lahir");
           

            try{
                Connection c = koneksi.getConnection();
                String sql="SELECT * FROM member";
                Statement s = c.createStatement();
                ResultSet rs = s.executeQuery(sql);
                while (rs.next())
                {
                tlayanan1.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                });
                }
                tabmember.setModel(tlayanan1);
                } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Ada Kesalahan pada tmember");
                }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butgrup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelGlass1 = new usu.widget.glass.PanelGlass();
        jLabel2 = new javax.swing.JLabel();
        kdmember = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nmmember = new javax.swing.JTextField();
        radL = new javax.swing.JRadioButton();
        radP = new javax.swing.JRadioButton();
        cmbttl = new uz.ncipro.calendar.JDateTimePicker();
        panelGlass2 = new usu.widget.glass.PanelGlass();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabmember = new javax.swing.JTable();
        panelGlass3 = new usu.widget.glass.PanelGlass();
        tinput = new javax.swing.JButton();
        tupdate = new javax.swing.JButton();
        tdelete = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Form Member");

        jLabel2.setText("Kode Member");

        kdmember.setEditable(false);

        jLabel3.setText("Nama");

        jLabel4.setText("Jenis Kelamin");

        jLabel5.setText("Tanggal Lahir");

        nmmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmmemberActionPerformed(evt);
            }
        });

        butgrup1.add(radL);
        radL.setText("L");

        butgrup1.add(radP);
        radP.setText("P");

        cmbttl.setDisplayFormat("  yyyy-MM-dd");

        javax.swing.GroupLayout panelGlass1Layout = new javax.swing.GroupLayout(panelGlass1);
        panelGlass1.setLayout(panelGlass1Layout);
        panelGlass1Layout.setHorizontalGroup(
            panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGlass1Layout.createSequentialGroup()
                        .addComponent(radL)
                        .addGap(18, 18, 18)
                        .addComponent(radP))
                    .addComponent(kdmember, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nmmember, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbttl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        panelGlass1Layout.setVerticalGroup(
            panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kdmember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nmmember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(radL)
                    .addComponent(radP))
                .addGap(18, 18, 18)
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbttl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tabmember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabmember);

        javax.swing.GroupLayout panelGlass2Layout = new javax.swing.GroupLayout(panelGlass2);
        panelGlass2.setLayout(panelGlass2Layout);
        panelGlass2Layout.setHorizontalGroup(
            panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelGlass2Layout.setVerticalGroup(
            panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        tinput.setBackground(new java.awt.Color(255, 255, 51));
        tinput.setText("Input");
        tinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinputActionPerformed(evt);
            }
        });

        tupdate.setBackground(new java.awt.Color(255, 255, 51));
        tupdate.setText("Update");
        tupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tupdateActionPerformed(evt);
            }
        });

        tdelete.setBackground(new java.awt.Color(255, 255, 51));
        tdelete.setText("Delete");
        tdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGlass3Layout = new javax.swing.GroupLayout(panelGlass3);
        panelGlass3.setLayout(panelGlass3Layout);
        panelGlass3Layout.setHorizontalGroup(
            panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tinput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(tupdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tdelete)
                .addContainerGap())
        );
        panelGlass3Layout.setVerticalGroup(
            panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tupdate)
                    .addComponent(tinput)
                    .addComponent(tdelete))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(panelGlass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelGlass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelGlass3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel1)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(panelGlass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGlass3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGlass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nmmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmmemberActionPerformed
        // TODO add your handling code here:       
    }//GEN-LAST:event_nmmemberActionPerformed

    private void tupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tupdateActionPerformed
        // TODO add your handling code here:
        String gender = null;
        if(radL.isSelected()){
        gender ="L";}
        else if(radP.isSelected()){
        gender="P";}
        try{
            Connection c = koneksi.getConnection();
            String sql;
            sql = "UPDATE `salon`.`member` SET `Nama_member` = '"+nmmember.getText()+"', `jenis_kel` = '"+gender+"', "
                    +   "`Tgl_Daftar` = '"+cmbttl.getSelectedItem()+"' WHERE "
                    +   "`member`.`kd_member` = '"+kdmember.getText()+"';";
            Statement s = c.createStatement();
            int r = s.executeUpdate(sql);
            nmmember.setText("");
            tabmember();
            AutoNomor();
            JOptionPane.showMessageDialog(null,"Data Pegawai sudah DiMasukan");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan :"+e.getMessage());
        }
    }//GEN-LAST:event_tupdateActionPerformed

    private void tinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinputActionPerformed
        // TODO add your handling code here:
        String gender = null;
        if(radL.isSelected()){
        gender ="L";}
        else if(radP.isSelected()){
        gender="P";}
        try{
            Connection c = koneksi.getConnection();
            String sql;
            sql = "INSERT INTO `salon`.`member` (`kd_member`, `Nama_member`, `jenis_kel`, `Tgl_Lahir`) VALUES ('"+kdmember.getText()+"', '"+nmmember.getText()+"', '"+gender+"', '"+cmbttl.getSelectedItem()+"');";
            Statement s = c.createStatement();
            int r = s.executeUpdate(sql);
            nmmember.setText("");
            AutoNomor();
            tabmember();
            JOptionPane.showMessageDialog(null,"Data Pegawai sudah DiMasukan");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan :"+e.getMessage());
        }
    }//GEN-LAST:event_tinputActionPerformed

    private void tdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdeleteActionPerformed
        // TODO add your handling code here:
        String gender = null;
        if(radL.isSelected()){
        gender ="L";}
        else if(radP.isSelected()){
        gender="P";}
        try{
            Connection c = koneksi.getConnection();
            String sql;
            sql = "DELETE FROM `salon`.`member` WHERE `member`.`kd_member` = '"+kdmember.getText()+"';";
            Statement s = c.createStatement();
            int r = s.executeUpdate(sql);
            nmmember.setText("");
            tabmember();
            AutoNomor();
            JOptionPane.showMessageDialog(null,"Data Pegawai sudah DiMasukan");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan :"+e.getMessage());
        }
    }//GEN-LAST:event_tdeleteActionPerformed

     public void AutoNomor() {
        try {
            Connection c = koneksi.getConnection();
            Statement stt = c.createStatement();
            String sql = "SELECT * FROM member ORDER BY kd_member DESC";
            try (ResultSet rs = stt.executeQuery(sql)) {
                if (rs.next()) {
                    String kd_member = rs.getString("kd_member").substring(2);
                    String AN = "" + (Integer.parseInt(kd_member) + 1);
                    String Nol = "";
                    
                    if(AN.length()==1)
                    {Nol = "00";}
                    else if(AN.length()==2)
                    {Nol = "0";}
                    else if(AN.length()==3)
                    {Nol = "";}
                    kdmember.setText("MB" + Nol + AN);//sesuaikan dengan variable namenya
                } else {
                    kdmember.setText("MB001");//sesuaikan dengan variable namenya
                }
            }
        } catch (SQLException | NumberFormatException e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup butgrup1;
    private uz.ncipro.calendar.JDateTimePicker cmbttl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kdmember;
    private javax.swing.JTextField nmmember;
    private usu.widget.glass.PanelGlass panelGlass1;
    private usu.widget.glass.PanelGlass panelGlass2;
    private usu.widget.glass.PanelGlass panelGlass3;
    private javax.swing.JRadioButton radL;
    private javax.swing.JRadioButton radP;
    private javax.swing.JTable tabmember;
    private javax.swing.JButton tdelete;
    private javax.swing.JButton tinput;
    private javax.swing.JButton tupdate;
    // End of variables declaration//GEN-END:variables
}
