/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salon.indeks;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import salon.koneksi.koneksi;

/**
 *
 * @author Muhammad Husni Farid
 */
public class pgwai extends javax.swing.JInternalFrame {

    /**
     * Creates new form pgwai
     */
    public pgwai() {
        initComponents();
        ttpegawai();
    }
    
    private void ttpegawai(){
       DefaultTableModel tlayanan1 = new DefaultTableModel();
            tlayanan1.addColumn("ID Pengguna Sistem");
            tlayanan1.addColumn("Nama");
            tlayanan1.addColumn("Jenis Kelamin");
            tlayanan1.addColumn("Jabatan");
            tlayanan1.addColumn("tanggal Lahir");
           

            try{
                Connection c = koneksi.getConnection();
                String sql="SELECT * FROM `p_sistem`";
                Statement s = c.createStatement();
                ResultSet rs = s.executeQuery(sql);
                while (rs.next())
                {
                tlayanan1.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
                });
                }
                tpegawai.setModel(tlayanan1);
                } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Ada Kesalahan");
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tpegawai = new javax.swing.JTable();
        panelGlass1 = new usu.widget.glass.PanelGlass();
        jLabel14 = new javax.swing.JLabel();
        txtidpegawai = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtnmpegawai = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        rlaki = new javax.swing.JRadioButton();
        rperempuan = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        cmbjabatan = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        cmbdate = new uz.ncipro.calendar.JDateTimePicker();
        panelGlass2 = new usu.widget.glass.PanelGlass();
        tmbinput = new javax.swing.JButton();
        tmbdelete = new javax.swing.JButton();
        tmbupdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Form Pegawai");

        jPanel3.setBackground(new java.awt.Color(255, 153, 255));

        tpegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tpegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpegawaiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tpegawai);

        jLabel14.setText("ID");

        jLabel15.setText("Nama");

        jLabel16.setText("Jenis Kelamin");

        rlaki.setText("Laki-laki");
        rlaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rlakirlakiActionPerformed(evt);
            }
        });

        rperempuan.setText("Perempuan");

        jLabel17.setText("Jabatan");

        cmbjabatan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-pilih-", "Manajer", "Kasir", "Pegawai", " " }));

        jLabel18.setText("Tanggal Lahir");

        cmbdate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2016-06-06" }));
        cmbdate.setDisplayFormat("yyyy-MM-dd");

        javax.swing.GroupLayout panelGlass1Layout = new javax.swing.GroupLayout(panelGlass1);
        panelGlass1.setLayout(panelGlass1Layout);
        panelGlass1Layout.setHorizontalGroup(
            panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass1Layout.createSequentialGroup()
                        .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelGlass1Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtidpegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelGlass1Layout.createSequentialGroup()
                                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnmpegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cmbjabatan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelGlass1Layout.createSequentialGroup()
                                            .addComponent(rlaki)
                                            .addGap(18, 18, 18)
                                            .addComponent(rperempuan))
                                        .addComponent(cmbdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(53, 53, 53))
                    .addGroup(panelGlass1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelGlass1Layout.setVerticalGroup(
            panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidpegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnmpegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rlaki)
                    .addComponent(rperempuan)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cmbdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        tmbinput.setBackground(new java.awt.Color(255, 255, 51));
        tmbinput.setText("Input");
        tmbinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmbinputtmbinput4ActionPerformed(evt);
            }
        });

        tmbdelete.setBackground(new java.awt.Color(255, 255, 51));
        tmbdelete.setText("Delete");
        tmbdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmbdeleteActionPerformed(evt);
            }
        });

        tmbupdate.setBackground(new java.awt.Color(255, 255, 51));
        tmbupdate.setText("Update");
        tmbupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmbupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGlass2Layout = new javax.swing.GroupLayout(panelGlass2);
        panelGlass2.setLayout(panelGlass2Layout);
        panelGlass2Layout.setHorizontalGroup(
            panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGlass2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(tmbinput, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGlass2Layout.createSequentialGroup()
                        .addComponent(tmbdelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tmbupdate)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGlass2Layout.setVerticalGroup(
            panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmbdelete)
                    .addComponent(tmbupdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tmbinput, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setText("Informasi Pengguna Sistem");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelGlass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGlass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(130, 130, 130))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(panelGlass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelGlass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tmbdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbdeleteActionPerformed
        // TODO add your handling code here:
        try{
            Connection c = koneksi.getConnection();
            String sql;
            sql = "DELETE FROM `salon`.`p_sistem` WHERE `p_sistem`.`ID_PS` = '"+txtidpegawai.getText()+"';";
            Statement s = c.createStatement();
            int r = s.executeUpdate(sql);
            ttpegawai();
            JOptionPane.showMessageDialog(null,"Data sudah dihapus");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan :"+e.getMessage());
        }
    }//GEN-LAST:event_tmbdeleteActionPerformed

    private void tmbupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbupdateActionPerformed
        // TODO add your handling code here:
        String gender = null;
        if(rlaki.isSelected())
        gender ="Laki-laki";
        else if(rperempuan.isSelected())
        gender="Perempuan";
        try{
            Connection c = koneksi.getConnection();
            String sql;
            sql = "UPDATE `salon`.`p_sistem` SET `nama_PS` = '"+txtnmpegawai.getText()+"', `jenis_kel` = '"+gender+"', "
            +   "`jabatan` = '"+cmbjabatan.getSelectedItem()+"', `tgl_lahir` = '"+cmbdate.getSelectedItem()+"' "
            +   "WHERE `p_sistem`.`ID_PS` = '"+txtidpegawai.getText()+"';";
            Statement s = c.createStatement();
            int r = s.executeUpdate(sql);
            ttpegawai();
            JOptionPane.showMessageDialog(null,"Data sudah diubah");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan :"+e.getMessage());
        }
    }//GEN-LAST:event_tmbupdateActionPerformed

    private void tmbinputtmbinput4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbinputtmbinput4ActionPerformed
        // TODO add your handling code here:
        String gender = null;
        if(rlaki.isSelected())
        gender ="Laki-laki";
        else if(rperempuan.isSelected())
        gender="Perempuan";
        try{
            Connection c = koneksi.getConnection();
            String sql;
            sql = "INSERT INTO `salon`.`p_sistem` (`ID_PS`, `nama_PS`, `jenis_kel`, `jabatan`, `tgl_lahir`) VALUES"
            +"('"+txtidpegawai.getText()+"', '"+txtnmpegawai.getText()+"', '"+gender+"', '"+cmbjabatan.getSelectedItem()+"', '"+cmbdate.getSelectedItem()+"');";
            Statement s = c.createStatement();
            int r = s.executeUpdate(sql);
            ttpegawai();
            txtidpegawai.setText("");
            txtnmpegawai.setText("");
            JOptionPane.showMessageDialog(null,"Data Pegawai sudah DiMasukan");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan :"+e.getMessage());
        }
    }//GEN-LAST:event_tmbinputtmbinput4ActionPerformed

    private void tpegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpegawaiMouseClicked
        // TODO add your handling code here:
        int table=tpegawai.getSelectedRow();
        String a=tpegawai.getValueAt(table, 0).toString();
        txtidpegawai.setText(a);
    }//GEN-LAST:event_tpegawaiMouseClicked

    private void rlakirlakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rlakirlakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rlakirlakiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private uz.ncipro.calendar.JDateTimePicker cmbdate;
    private javax.swing.JComboBox cmbjabatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private usu.widget.glass.PanelGlass panelGlass1;
    private usu.widget.glass.PanelGlass panelGlass2;
    private javax.swing.JRadioButton rlaki;
    private javax.swing.JRadioButton rperempuan;
    private javax.swing.JButton tmbdelete;
    private javax.swing.JButton tmbinput;
    private javax.swing.JButton tmbupdate;
    private javax.swing.JTable tpegawai;
    private javax.swing.JTextField txtidpegawai;
    private javax.swing.JTextField txtnmpegawai;
    // End of variables declaration//GEN-END:variables
}
